module ColorHelper
    def set_color
        if @current_app
          @color = @current_app.app_color
        end
    end

    def set_app_color
        if @current_app
            case @color
            when "red"
                @text_color = "text-dark"
                @body_bg_color = "background: rgb(255, 200, 213);"
                @card_header_bg_color = "background: rgb(255, 43, 43);"
                @card_header_text_color = "text-dark"
                @card_bg_corlor = "background: rgb(255, 200, 213);"
                @card_text_color = "text-dark"
                @nav_bg_color = "background: rgb(255, 43, 43);"
                @nav_text_color= "text-light"
                @accordion_header_bg_color = "background: rgb(255, 43, 43);"
                @accordion_header_text_color = "text-light"
                @accordion_bg_color = "background: rgb(220, 220, 220);"
                @accordion_text_color = "text-dark"
                @border_color = "border-danger"
            when "blue"
                @text_color = "text-dark"
                @body_bg_color = "background: rgb(225, 248, 248);"
                @card_header_bg_color = "background: rgb(0, 46, 252);"
                @card_header_text_color = "text-light"
                @card_bg_corlor = "background: rgb(255, 248, 248);"
                @card_text_color = "text-dark"
                @nav_bg_color = "background: rgb(0, 46, 252);"
                @nav_text_color = "text-light"
                @accordion_header_bg_color = "background: rgb(0, 46, 252);"
                @accordion_header_text_color = "text-light"
                @accordion_bg_color = "background: rgb(255, 248, 248);"
                @accordion_text_color = "text-dark"
                @border_color = "border-primary"
            when "yellow"
                @text_color = "text-dark"
                @body_bg_color = "background: rgb(253, 249, 184);"
                @card_header_bg_color = "background: rgb(255, 208, 0);"
                @card_header_text_color = "text-dark"
                @card_bg_corlor = "background: rgb(253, 249, 183);"
                @card_text_color = "text-dark"
                @nav_bg_color = "background: rgb(255, 208, 0);"
                @nav_text_color = "text-dark"
                @accordion_header_bg_color = "background: rgb(255, 208, 0);"
                @accordion_header_text_color = "text-dark"
                @accordion_bg_color = "background: rgb(253, 249, 183);"
                @accordion_text_color = "text-dark"
                @border_color = "border-warning"
            when "green"
                @text_color = "text-dark"
                @body_bg_color = "background: rgb(211, 255, 211);"
                @card_header_bg_color = "background: rgb(34, 235, 16);"
                @card_header_text_color = "text-dark"
                @card_bg_corlor = "background: rgb(211, 255, 211);"
                @card_text_color = "text-dark"
                @nav_bg_color = "background: rgb(34, 235, 16);"
                @nav_text_color = "text-dark"
                @accordion_header_bg_color = "background: rgb(34, 235, 16);"
                @accordion_header_text_color = "text-dark"
                @accordion_bg_color = "background: rgb(211, 255, 211);"
                @accordion_text_color = "text-dark"
                @border_color = "border-success"
            when "black"
                @text_color = "text-light"
                @body_bg_color = "background: rgb(0, 0, 0);"
                @card_header_bg_color = "background: rgb(133, 133, 133);"
                @card_header_text_color = "text-white"
                @card_bg_corlor = "background: rgb(180, 180, 180);"
                @card_text_color = "text-dark"
                @nav_bg_color = "background: rgb(133, 133, 133);"
                @nav_text_color = "text-light"
                @accordion_header_bg_color = "background: rgb(133, 133, 133);"
                @accordion_header_text_color = "text-white"
                @accordion_bg_color = "background: rgb(180, 180, 180);"
                @accordion_text_color = "text-dark"
                @border_color = "border-light"
            else
                @text_color = "text-dark"
                @body_bg_color = "background: rgb(225, 248, 248);"
                @card_header_bg_color = "background: rgb(67, 229, 250);"
                @card_header_text_color = "text-dark"
                @card_bg_corlor = "background: rgb(225, 248, 248);"
                @card_text_color = "text-dark"
                @nav_bg_color = "background: rgb(67, 229, 250);"
                @nav_text_color = "text-dark"
                @accordion_header_bg_color = "background: rgb(67, 229, 250);"
                @accordion_header_text_color = "text-dark"
                @accordion_bg_color = "background: rgb(225, 248, 248);"
                @accordion_text_color = "text-dark"
                @border_color = "border-dark"
            end  
        else
            @text_color = "text-dark"
            @body_bg_color = "background: rgb(225, 248, 248);"
            @card_header_bg_color = "background: rgb(67, 229, 250);"
            @card_header_text_color = "text-dark"
            @card_bg_corlor = "background: rgb(225, 248, 248);"
            @card_text_color = "text-dark"
            @nav_bg_color = "background: rgb(67, 229, 250);"
            @nav_text_color = "text-dark"
            @accordion_header_bg_color = "background: rgb(67, 229, 250);"
            @accordion_header_text_color = "text-dark"
            @accordion_bg_color = "background: rgb(225, 248, 248);"
            @accordion_text_color = "text-dark"
        end
    end
    
end

